[net]
git-fetch-with-cli = true

# Prefer wild linker on x86_64/aarch64 Linux when available.
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=--ld-path=/usr/local/bin/wild"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=--ld-path=/usr/local/bin/wild"]
